### ISSUE TITLE
the vertical curve is not created

### ISSUE THREAD

**Issue by retsyo** [johnhw/blender_knots#1]
I am using this, but the vertical line is not created
and the middle horizontal line has 3 bend as expected, however the top and bottom horizontal lines are straight which is unexpected 

```text
                  
            v     
         >--|--+  
         ^  |  |  
         |  |  |  
       >-|-----|->
         |  |  |  
         |  |  |  
         +--|--+  
            |     
            v     
```

**Comment by johnhw** [comment]
The code didn't handle lower case v properly (was expecting upper case V). This is fixed now.
